### ISSUE TITLE
Filters

### ISSUE THREAD

**Issue by dmfs** [codeka/carrot#11]
Any plans to add support for filters like in Jinja (see http://jinja.pocoo.org/docs/2.9/templates/#filters)?

**Comment by codeka** [comment]
I never really liked that syntax, I added the function syntax because I find it much more natural than filters.

For example, the HtmlHelper class adds stuff like `{{ html.escape("string") }}` would be like `{{ "string" | escape }}`.

I was planning to add a bunch of extra helpers. So like instead of `{{ mytext|indent(2, true) }}` you could have `{{ text.indent("blah", 2, true) }}`

**Comment by dmfs** [comment]
Fair enough. I don't have any strong feelings for either version. The filter syntax reminds me of the pipe operator on un*x shells hence it feels a bit more natural to me. But the function syntax will do just as well.
